In [1]:
import numpy as np
d = {1:0.5, 0:0.1}
policy=np.eye(5)[np.random.randint(0,5,25)]
np.vectorize(d.get)(policy)

array([[0.1, 0.1, 0.1, 0.5, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.5],
       [0.5, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.5],
       [0.1, 0.1, 0.1, 0.5, 0.1],
       [0.5, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.5],
       [0.5, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.5, 0.1, 0.1],
       [0.1, 0.5, 0.1, 0.1, 0.1],
       [0.5, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.5, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.5, 0.1],
       [0.5, 0.1, 0.1, 0.1, 0.1],
       [0.5, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.5, 0.1, 0.1],
       [0.5, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.5],
       [0.1, 0.1, 0.5, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.5],
       [0.5, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.5, 0.1, 0.1, 0.1],
       [0.1, 0.5, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.5, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.5, 0.1]])

In [3]:
state=np.array([[j,i] for i in range(5) for j in range(5)])
state

array([[0, 0],
       [1, 0],
       [2, 0],
       [3, 0],
       [4, 0],
       [0, 1],
       [1, 1],
       [2, 1],
       [3, 1],
       [4, 1],
       [0, 2],
       [1, 2],
       [2, 2],
       [3, 2],
       [4, 2],
       [0, 3],
       [1, 3],
       [2, 3],
       [3, 3],
       [4, 3],
       [0, 4],
       [1, 4],
       [2, 4],
       [3, 4],
       [4, 4]])

In [10]:
np.hstack((a//3,a%3))

array([[2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.]])